### ISSUE TITLE
NEW LOGO

### ISSUE THREAD

**Issue by rijal10** [jamiebuilds/anti-fascist-mit-license#13]
Hello jamiebuilds.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by caxvis** [comment]
First of all, it's not an app, it's a **license**.

Secondly, here's my idea for the logo : 

![af-license](https://user-images.githubusercontent.com/34530026/42318285-b9058268-8078-11e8-9022-1cc4d1a5a243.png)

> Credit expected 😝
