### ISSUE TITLE
Anti-fascism may be mistaken for fascism itself

### ISSUE THREAD

**Issue by WilliamVenner** [jamiebuilds/anti-fascist-mit-license#14]
For example, this license appears to restrict and/or target people who have right-wing leaning political beliefs who do not necessarily identify as fascists, or support fascism, which is therefore restricting people's political freedom (in the context of using this licenses' software) which means this license may be mistaken for fascism itself.

I would recommend removing the explicit mention of Donald Trump, as Donald Trump is not conclusively a fascist, nor has ever identified as one, and those that support Donald Trump are also not conclusively supporting fascism or are fascists themselves.

I am in support of any anti-fascist movement which seeks to protect people's political freedoms while remaining reasonable and respecting people's human rights.

**Comment by jamiebuilds** [comment]
Donald Trump is a fascist whether he admits it or not. Those supporting him support fascism whether they realize it or not.
