### ISSUE TITLE
What about repented fascists?

### ISSUE THREAD

**Issue by julien-f** [jamiebuilds/anti-fascist-mit-license#3]
*errare humanum est* :slightly_smiling_face:

**Comment by lrn2prgrm** [comment]
Reminds me about this one: https://www.json.org/license.html
https://en.wikipedia.org/wiki/Douglas_Crockford#%22Good,_not_Evil%22

**Comment by jamiebuilds** [comment]
I don't think it'd be possible to enforce anything that happened prior to the use of my code. So I don't think I have to do anything here
