### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by AntifaPizza** [jamiebuilds/anti-fascist-mit-license#4]
Jamie, you seem like a strong leader who can help push everyone towards this single anti-facism ideology. 

I think we can all appreciate your autocratic approach to this problem. I can't think of a better person than you to dictate these kinds of decisions of who is and isn't a facist.

The only thing I'm concerned about is how we'll keep track of all these facists??? Perhaps you should assemble of list of suspected facists and we can coordinate on the best way to round up these people for "reeducation"? 

Anyway, I just wanted to let you know that you are right and absolute in your power and self appointed authority.

**Comment by jamiebuilds** [comment]
At least you had fun
