### ISSUE TITLE
(Identity) Politics has no place in tech

### ISSUE THREAD

**Issue by watkinsr** [jamiebuilds/anti-fascist-mit-license#8]
If it wasn't bad enough that the leftists managed to ruin academia and various other hopeful places such as California, they have started to spread their leftism into the ranks of open source software. 

I should hope that any given competent developer would not let these people who only believe in power hierarchies take all your freedoms away from you. This licence is a joke and the ONLY free licence is the GNU GPL 3.0 licence.

Let this issue serve as a reminder to everybody that free speech and the ability to express yourself freely, regardless of political stance, is a freedom given to those earned by their ancestors in war time, who knew better than this guy who has made this terrible repository.

Lest we remember that political echo chambers never end well. The leftists are happy to advocate for full scale communism, very much like the soviets. They are all about power.

**Comment by jamiebuilds** [comment]
Your assertion in the title is incorrect, and I didn't read the rest so
