### ISSUE TITLE
This licence is unusable

### ISSUE THREAD

**Issue by faissaloo** [jamiebuilds/anti-fascist-mit-license#9]
It could be argued in court that the payment of taxes in the US, China or israel comes under 'supporting fascists', I don't believe this was the intention of the licence so a clause should be added exempting coercion and/or 'willful' should be used to qualify 'support' along with an additional definition of 'willful'.

**Comment by GithubIsAwful** [comment]
I recommend the authour stop trying to use Free Software to restrict the freedom of users and of software.

**Comment by jamiebuilds** [comment]
@GithubIsAwful you are free not to use my software, and I don't owe you a thing.
